### ISSUE TITLE
DTV uses http GET, not POST

### ISSUE THREAD

**Issue by vmweaver** [bklavet/Echo-skill-to-control-Directv#1]
I couldn't find a better way to comment on this. I am testing your code now, but I believe you should be using the GET method, not POST in you dtv api calls.

**Comment by bklavet** [comment]
Hello mawrew19,  I believe at the time I tried Get as well, but did not have any luck.  I was able to have the echo access the skill, and reply with the correct confirmation, but the skill would not send off the URL to the directv receiver.  I was hoping for this to work without the need for a pc running as an end point.  If you can figure this out, it would be a cool setup.

**Comment by vmweaver** [comment]
I was able to get this to work last night with my DTV box on the internet. Of course this doesn't have any type of security on it, so I will be working on some type of DMZ (RPi) system to provide a layer of security.  Thanks for your work on this.

**Comment by bklavet** [comment]
Wow!  that is exciting.  All you had to do was change the POST to Get?  I swear I tried that and saw no difference.  I am super excited for you though!  If you could do me a favor, set up a youtube video and drop me a link so I can see this happening! have a great one.

**Comment by vmweaver** [comment]
I will take a look at all of the files I have and compare to yours on
github.

**Comment by bklavet** [comment]
Thanks mawrew19

**Comment by bklavet** [comment]
I think it has to be more to it than changing the POSTs to Gets.  I updated my index to have GET instead of POST and uploaded to aws lambda,  when I run tests on the Alexa skill simulator I don't get anything from lambda,  do you get a confirmation message from lambda that alexa replies to?  When your directv receiver executes a command does Alexa reply with an "okay"?

If it does perform the action with no voice response, that would be alright with me, and would help explain why I stuck to the POST and figured GET wouldn't work.  If you aren't getting a reply..then things have to change a bit in the code.

**Comment by vmweaver** [comment]
I have mine completely working now. I have tweaked it a bit and will upload
the code to github, but there were not many changes needed for
functionality.  I will also try to document my test case since that's
something that took me some time to resolve.

Based on the the Skill, Alexa does not say okay or confirm anything
(IIRC).  I will also be looking to add channel selection to it.. so "Alexa,
Tell TV to change to CNN" or "Alexa, Tell TV to Change to channel 230".
I will put more info together and share once I tidy it up a bit.

**Comment by bklavet** [comment]
mawrew19!  Please do put your working version to GitHub.  I am really curious to see what you have going.  Channel selection would be a great feature!  I strayed away from this when I found the armzilla-bridge... I was able to put a handful of the url commands on a Rpi and have the echo do a few key things.  The skill method is soo much more desirable do to it's expandability for voice commands, and having everything in lambda means no more resetting rpi when the power goes out.  Please throw me a link here so I can try and keep up!  Good Job!

**Comment by vmweaver** [comment]
Files updated...

**Comment by bklavet** [comment]
I added you as a collaborator so hopefully you will be able to make changes.

**Comment by vmweaver** [comment]
​updated...​

**Comment by bklavet** [comment]
mawrew19 you are a genius! added your updated index file.  Testing is working through the Alexa skill testing.  Thanks for adding to the Readme file while this was all still fresh in your mind.  can't wait to get home and try this out for real.

**Comment by bklavet** [comment]
I added some network presets to the index file A&E, AMC, Animal Planet, BET, Bravo, Comedy Central, C span, Cartoon Network, Discovery, Disney Channel, Disney Junior, Disney XD, Food Network, FOX, FX, HGTV, History, Lifetime, MSNBC, MTV, MTV2, National Geographic, Nick Jr., Spike, SyFy, TBS, TNT, truTV, VH1, ESPN, and ESPN 2.   also updated the sample utterances to reflect this.

I'm going to test this out at home, and if it works I will update the existing INDEX and Sample Utterances.

**Comment by vmweaver** [comment]
That's great!  
I am also working on a tweak to specify any channel by number. Working well for me right now, but will need to do some more testing.  Will require an update to the intent, utterances, and index and is a very simple change.

**Comment by bklavet** [comment]
I am hit and miss with the presets.... They test fine, but the utterance need more work. My accuracy with the skill is pretty bad.  Hopefully your channel number search will be a lot better, since numbers are easier for Alexa to discern.

**Comment by vmweaver** [comment]
Will poke at it tomorrow and push an update.  Will also look at you enhancements....

**Comment by vmweaver** [comment]
@bklavet 

Updated Index, SampleUtterance, and Intents for changing channel by number.

"Alexa, tell TV (what I call mine) channel 220"

If you use the AWS Alexa Service Simulator you could put in:

"Tell TV channel two twenty"

We can add some utterances to make it more like "change to channel 220" or something like that.

Please test it out a let me know how it goes.

**Comment by bklavet** [comment]
Sorry about the delay in response, was out of town.  I can't wait to test this out tomorrow, will let you know.  so far looks really great!

Thanks

**Comment by bklavet** [comment]
AMAZON.NUMBERS.   I wasn't able to find the documentation for this type.  Do you have a link for it.  I would like to read up on it.  I am really impressed that the sample utterance can be so minimal.  I will be trying this out tonight.  Does this type decipher numbers that use "O" instead of "0"?  I am one of those people that would say  "2" "O" "2", instead of "2" "0" "2".

**Comment by vmweaver** [comment]
It converts spoken numbers in to real numbers.:
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/defining-the-voice-interface
search on the page for Amazon.numbers. No much info there, but should require some testing.

I think it will recognize "two two oh", "two hundred twenty", "two twenty" all as 220.

**Comment by ChipHappens** [comment]
Numbers understands both "oh" and zero"

**Comment by bklavet** [comment]
Thanks!,  Just looking at this quickly... looks like the Literal type has been changed to AMAZON.LITERAL.  Maybe the the sample utterances could be made more simplistic as well.  
Backward Compatibility 

_The LITERAL slot type continues to work. To continue using the old functionality, specify AMAZON.LITERAL for the slot type in the intent schema and leave the slot values within the sample utterances. 

Migrating to a custom slot type is recommended, as it is easier to define the sample utterances and achieve better accuracy._ 

I really like how you added the slot "channel" to the intent.  I am thinking that format for a network search, would be a much cleaner solution too.  

I tested out the channel search and it is testing perfectly.  I will try it out at home.  
Really happy with how this is going. 
Thanks again.

**Comment by vmweaver** [comment]
My ideas on doing the channel by name is to use a custom slot type.  More testing to do when my wife doesn't want to watch much TV.. ;-)

**Comment by bklavet** [comment]
mawrew19,
was looking at the custom slot and that looks like a great idea. In fact that may work better for the remote control buttons too.  I am going to mess around with a couple networks aswell and see how it goes.

**Comment by ufccowboyfan** [comment]
Have been following along with the youtube tutorial but don't know what to do with the port forwarding or DMZ. I have an apple extreme router but not very familiar with these options that are required for Alexa to talk to the Directv receiver. Any chance you can provide more step by step instructions on how to do that DMZ or portfoward to make this work. Thanks

**Comment by bklavet** [comment]
Ufccowboyfan,

First thing I would try, is to make sure you can control your receiver from within your lan. Fill in your ip (the directv's ip address) and place it in a browser address bar on a computer working on the same lan as your directv receiver.
http://xxx.xxx.xxx.xxx:8080/remote/processKey?key=pause&hold=keyPress

This should pause the receiver.  If that works, then replace the directv's ip with your wan ip, and try the command on a pc/phone that is on a different network.  If it works, you don't need to worry about it. If it don't google your router and how to port forward.

**Comment by bklavet** [comment]
I did a search on apple and dmz, it looks like apple calls the dmz, the Default Host. May want to search that too! Good luck
maybe try this if you can get into your router.
For port mapping, I would suggest the following:
•Service: leave default
•Public TCP Port(s): 8080
•Public UDP Port(s): (leave blank)
•Private IP Address: (this will be the IP address of your Directv receiver)
•Private TCP Port(s): 80
•Private UDP Port(s): (leave blank>)

any luck?

**Comment by mthom16** [comment]
Does this work with the DirectTV Genie and Genie Mini? If not what equipment do you have that works?

**Comment by mthom16** [comment]
Ok. It did work on the Genie, but only the main box. I don't know if you can use it on the mini boxes.

**Comment by bklavet** [comment]
Mthom16 you will need to add the mac of the mini to the index file.  Check out the issue How to control the mini genie.

**Comment by bearrowb** [comment]
thank you for all the details, this has been first skill and aws lamda use, because of all the work done, learning the skills and syntax seem to make sense now (somewhat) if you have many receivers or mini's, you will want to use DMZ for the main receiver all my mini are wireless child's to the parent, so the trick will be to give unique name to each, plus we need to get a the unique WVB client name or ID# or mac address, or whatever routes from receiver though WVB to mini, then we could enter custom lines with ip;8080;WVBpath#  this would let us say "alexa DirectvMain to channel 202" and "alexa DirectvBedroom to Channel 201" see i have two echo's and a Dot so having Main controlled by Echo and bedroom by Dot would be nice.  ------  then plan is solid the issue i have is the client list is just txt names in the main, look like DTV is has a hiding files for the name to path rule

**Comment by bklavet** [comment]
Hello,  I’m not following.
Your wireless minis that are connected to the main Genie should be controllable by the mac address or the clientAddr=[mac].
So to see what you have connected to the main and verify the mac address you would enter into a browser
http://[lan_IP]:8080/info/getLocations
this will/should show all the receivers and what the macs are.  The one that shows as ‘0’ is the main Genie.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bearrowb** [comment]
Thank you, will try that in string to control different units via custom unit names

**Comment by bklavet** [comment]
Sure thing,
If it was me, I would create a separate  skill for each receiver you want to control.  The Invocation name would be unique to each receiver.
So the invocation name for the main tv, might be “TV”, and the bedroom invocation name could be “John’s TV”.  Each invocation name would point to it’s own skill and go off to it’s unique lambda function.

Personally I think it would be easier to learn a separate  invocation name for the receivers than having to train myself to add descriptive language to the echo on what receiver I am using, not to mention all the other sample utterances that would need to be created to get this to work.

I am currently working with another who is trying to get there mini working.  If you get stuck let me know, I will do my best to help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
