### ISSUE TITLE
LAMBDA Response: The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by hellohowareyougood** [bklavet/Echo-skill-to-control-Directv#11]
Hello all and thank you for this. I am new to all of this and was able to set it up per the instructions and youtube video. When I test it in Alexa Skit Set, I get this message "The remote endpoint could not be called, or the response it returned was invalid"

I am aware that this means it cannot connect from an outside network. I have port forwarded the directv on the router with port 8080. 

In the index file, I do not need to to put the local IP address for the directv box (10.0.1.5)? Any other suggestions would be great. Thank you!!

**Comment by bklavet** [comment]
Hello, the var local_ip needs to be your wan ip address.  Best way to find this is to do a web search and google "what's my ip" and in the results it will show your wan ip.  Give that a try and let me know if that does the trick.

If that doesn't work the next thing to sort out is if you can control the receiver from within your home network. On a computer connected to the same network as you receiver open a browser and enter this and hit enter.
http://10.0.1.5:8080/remote/processKey?key=pause&hold=keyPress
This should pause the receiver.
If it does alter the ip address to your wan ip and try the command from another network than your directv. 
Report back if you are able to do this from both your local network and outside network.

**Comment by hellohowareyougood** [comment]
Thanks for the response. 

http://10.0.1.5:8080/remote/processKey?key=pause&hold=keyPress works from within the network. 

using the WAN IP does not work.

**Comment by hellohowareyougood** [comment]
I can access other devices using my public WAN (IP cameras, thermostat, etc). However, using port 8080, I cannot access any devices.

**Comment by bklavet** [comment]
double check that the receiver is set to "allow".
on the receiver go to Menu->System Setup->Whole-Home->External Device.  make sure allow is selected.

Then double check that port 8080 is forwarded, or throw 10.0.1.5 into your DMZ and try, if you cannot send the pause command from outside your network the skill will not work.

**Comment by hellohowareyougood** [comment]
I can now access it remotely. I checked the external device and it is set to allow. 

However, when using service simulator, I am still getting ""The remote endpoint could not be called, or the response it returned was invalid"

Do I need to set port 8080 anywhere in the index file?

**Comment by hellohowareyougood** [comment]
Also, when I test in LAMBDA, I get the following messages: 

{
  "errorMessage": "Cannot read property 'application' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "AlexaSkill.execute (/var/task/AlexaSkill:72:62)",
    "exports.handler (/var/task/index:351:20)"
  ]
}

**Comment by bklavet** [comment]
the only lines that need to be modified is 
var local_ip = 'XXX.XXX.XXX.XXX';
and the APP ID 
port 8080 is in the index file so you don't need to add that.  
when you put in a request in the simulator there are two boxes underneath, one shows what alexa is sending to lambda and the other is the response from lambda, what does the alexa box show when you type cnn in the simulator and hit enter?

Thanks

**Comment by hellohowareyougood** [comment]
{
  "session": {
    "sessionId": "SessionId.a68938a9-ac63-4720-acbb-f21305fb3719",
    "application": {
      "applicationId": "amzn1.ask.skill.a29fbe37-aa49-4ee5-83e2-a32a6b4d22d7"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AFH5ZINNYYP55AT5VTGEGDU275TB5HK4AOPHJ3KM7H5G6SO75RYO4KCSLO7CNCZF76CFYAQHE2MROCOGZA7ITJXAB7JBA7RH33OB3HZMRDWYIKWFS3MYGXOG2VFM6HKEXEL7ATLS7KFC6MGVOVXPTJ72L6TEBWFT4FTZ2IQGJRLDJ7VV6KV5ZJGT2BQ4K6UXL6O7SRSRTVBHJQY"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.2e70cba9-34cc-4a8d-b267-e576e1ea02c4",
    "locale": "en-US",
    "timestamp": "2016-10-20T02:53:01Z",
    "intent": {
      "name": "DirectvIntent",
      "slots": {
        "Control": {
          "name": "Control",
          "value": "CNN"
        },
        "Channel": {
          "name": "Channel"
        }
      }
    }
  },
  "version": "1.0"
}

**Comment by hellohowareyougood** [comment]
that's what it says in the alexa box

**Comment by hellohowareyougood** [comment]
and thank you very much for your help thus far:)

**Comment by bklavet** [comment]
so that looks the way I would expect it to. As long as you can now send commands through the wan ip from a different network than the your local network the directv receiver is on.  I would delete the lambda function and start over on the lambda side.  make sure that both the Alexa folder and Index file are placed in a zipp file.  It looks like there trouble is on the lambda side and not the alexa developer side.

**Comment by hellohowareyougood** [comment]
I deleted and readded. Still same issue. In LAMBA, when I run configure test event and then Alexa Smart Home Control, I get {
  "errorMessage": "Unexpected token ILLEGAL",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

**Comment by hellohowareyougood** [comment]
got it working. THANK YOU!!!!!!!!!

**Comment by bklavet** [comment]
That's Great!  Where was the problem?
