### ISSUE TITLE
Process exited before completing request

### ISSUE THREAD

**Issue by jswagaman63** [bklavet/Echo-skill-to-control-Directv#13]
I am working with the older Directv DVR, that has to have a Directv Cinema internet box attached.  I have gotten everything setup and my testing for commands that don't exist is successful.  I get the following error when I try to test a valid command.  I have tried setting up the IP address for Port Forwarding on my Netgear Router.  I am just not sure if it is a Port Forwarding issue or do I need to put my Directv outside my DMZ.  Any help you can provide would be most helpful.

START RequestId: edb06b5f-9dfc-11e6-b0e1-bd73d4b846ba Version: $LATEST
2016-10-29T17:27:12.904Z    edb06b5f-9dfc-11e6-b0e1-bd73d4b846ba    session applicationId: amzn1.ask.skill.7a2c15b5-0040-4d68-90c2-404f0ec9ee4e
2016-10-29T17:27:12.905Z    edb06b5f-9dfc-11e6-b0e1-bd73d4b846ba    dispatch intent = DirectvIntent
2016-10-29T17:27:13.098Z    edb06b5f-9dfc-11e6-b0e1-bd73d4b846ba    Error: socket hang up
    at createHangUpError (_http_client.js:200:15)
    at Socket.socketOnEnd (_http_client.js:285:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)
END RequestId: edb06b5f-9dfc-11e6-b0e1-bd73d4b846ba
REPORT RequestId: edb06b5f-9dfc-11e6-b0e1-bd73d4b846ba  Duration: 469.89 ms Billed Duration: 500 ms     Memory Size: 128 MB Max Memory Used: 6 MB  
Process exited before completing request

**Comment by bklavet** [comment]
Hello, 

so try this out and see if either will work.  this should narrow down two things.  One can your receiver be controlled locally within the network, and second is port 8080 forwarded and can the receiver be controlled from outside your network.
try this open a browser session and place this in the address bar, (edit [local_ip] with your directv's receivers local ip... or in this case the cinema internet box's ip.  you may have to add in the mac address if you have multiple receivers running that has been covered on other issues).
http://[local_ip]:8080/remote/processKey?key=pause&hold=keyPress
place this command in a browser window of a computer on your local network and hit enter. The directv receiver should pause.
next try to pause the receiver from outside your local network. alter the pause command to match your wan ip address. then open a browser and place this command and hit enter. Keep in mind this needs to be on a different network so from a cell phone or friends house.
http://[wan_ip]:8080/remote/processKey?key=pause&hold=keyPress
if the receiver pauses you have port 8080 forwarded and your ISP is not blocking port 8080.

**Comment by jswagaman63** [comment]
Thanks for the suggestions.  Essentially, I had to setup my cinema internet box as a DMZ server.  This allowed my port forwarding to work.  

Thank you for answering my question.  I really appreciate it.

**Comment by bklavet** [comment]
Glad it's working
