### ISSUE TITLE
Port problem?

### ISSUE THREAD

**Issue by jjmed33** [bklavet/Echo-skill-to-control-Directv#15]
Hi. Thanks for your tutorial. So, if the browser pause command works with the LAN IP but does not work with the WAN IP I am looking at a port problem? I have forwarded 8080 to my DirecTV receiver and placed it into DMZ with no success.

**Comment by thauch** [comment]
I would try DMZ first to verify it is working through the WAN. Then take it off DMZ and try through a port forward.

Don't do both at the same time. I've seen screwy things that way and there's no reason to port forward if it's DMZ.

**Comment by jjmed33** [comment]
Hey thauch., thanks for the response. Yeah, I worded my message poorly. I tried via port 8080, and that didn't work. So I deleted the port forward and tried DMZ. That didn't work either. I just want to make sure the my set up works and that it's the router/connection that is the problem. J.

**Comment by thauch** [comment]
If it works locally but not outside, it sounds like something in your router config. You can try something like canyouseeme.org and check for the port to be open.

**Comment by jjmed33** [comment]
For some reason all of my ports come up closed. I can't figure it out.

**Comment by reedh11** [comment]
Had it working yesterday, now today it won’t work and port 8080 is now not showing as open when I do a port check.  Nothing was changed on the router and direct tv receiver is showing as an allowed application when I check status. Any ideas?

**Comment by vmweaver** [comment]
And your port forwarding configuration is still on your router? Is your
router one that you are given with your service or is it one that you own?
I know you say you didn't change anything on your router, but did you
verify that config was still set up?

I wonder if your ISP detects and shuts down non-standard traffic patterns...

**Comment by vmweaver** [comment]
And....did your external address change, by chance?

**Comment by reedh11** [comment]
Don’t believe the IP address changed. It is a router provided by AT&T so that’s all I could think was happening. I verified the configuration and set it up several times the same way as I had before. Still showing the port is closed.

Sent from my iPhone

On Jan 11, 2018, at 8:49 PM, mawrew19 <notifications@github.com<mailto:notifications@github.com>> wrote:

And....did your external address change, by chance?

**Comment by vmweaver** [comment]
Can you please verify that your IP hasn't changed. That's about the only other explanation I can think of.  Just google "what's my ip" from a computer on your network.

**Comment by reedh11** [comment]
Yes i verified that the IP was the same.  But strangest thing, I did a port check late last night and it was open again.  Guess I'll see how long this time and if it closes again, would that mean the ISP is blocking it?

Thanks

**Comment by vmweaver** [comment]
possibly...  I wonder if the router is doing it? Do you have any access or event logs on the router?

**Comment by reedh11** [comment]
so at lunch i tested it some more.  It was open and working, however 2 or 3 failed alexa commands to power off, and the port then closed.  I wonder if there is a configuration or rule set up on the router.  I was looking at the event logs on the router last night but that is jibberish to me, as this is all very new to me.

**Comment by vmweaver** [comment]
Do you know what the model number and brand of the router is?  I may be able to go through some docs online and see if there is something there.

**Comment by reedh11** [comment]
Pace 5268AC

Thanks!

**Comment by vmweaver** [comment]
So, are you setting up a new application profile under Applications, Pinholes and DMZ in the router configuration to do your port forwarding?
 I assume you are and specifying source ports as from: 8080 and to: 8080 ?
I have seen some historical reports of ATT sometimes filtering 8080.  You could also try configuring the skill to point to another port number like 3000 and then on your rule configuration specify:
From: 3000   to: 3000
and then the "Map to Host Port" would just be "8080".  
This, essentially puts a listener on the Internet side on port 3000 for your skill to hit, then translates that port to 8080 on the inside of your network for your DTV box.

**Comment by reedh11** [comment]
Yes that’s exaxtly what I was doing.  I will try that and let you know.  Thanks

**Comment by reedh11** [comment]
Will I have to change anything in the skill index?

**Comment by vmweaver** [comment]
Yes...you will need to update the port in the index file to be 3000, then zip the files and re upload.

**Comment by reedh11** [comment]
as of right now this has only stopped working once, so it appears to be a good work around.  Still going to investigate if there is some sort of keep alive setting inside the router that I need to turn on.

Thanks again for your help.

**Comment by vmweaver** [comment]
Good deal. If you do figure out what was actually causing the issue, please comment to potentially help others!
Closing this thread.
