### ISSUE TITLE
Added a channel with a dash in it. It's not working.

### ISSUE THREAD

**Issue by eyoung71** [bklavet/Echo-skill-to-control-Directv#16]
First off, great tutorial! I followed it and had it up and running with no trouble at all.

My local NBC channel and other locals have a dash in the channel number. So NBC is channel 11-1.
So I added this line to the index:

                                case "NBC":
					path = '/tv/tune?major=11-1&minor=65535';
                
				break;

When I test it nothing happens. I am testing through Alexa developer website. 
I saved the index. Then I recreated the zip file and then loaded the zip file through lambda.
Any ideas?
I could be missing a step. This is the first channel I have tried to add.

**Comment by bklavet** [comment]
Hey, when you have the DTV on the local channel go to a browser and enter this
http://[localIP]:8080/tv/getTuned
you should get a reply that shows what program is currently on
what are your major and minor values?

**Comment by eyoung71** [comment]
{
  "callsign": "KCBDDT",
  "date": "20161107",
  "duration": 7200,
  "isOffAir": true,
  "isPclocked": 3,
  "isPpv": false,
  "isRecording": false,
  "isVod": false,
  "major": 11,
  "minor": 1,
  "offset": 334,
  "programId": "43794475",
  "rating": "TV-G",
  "startTime": 1478523600,
  "stationId": 1652265,
  "status": {
    "code": 200,
    "commandResult": 0,
    "msg": "OK.",
    "query": "/tv/getTuned"
  },
  "title": "Today"
}

So I added the channel as major=11&minor=1 and it worked!

**Comment by bklavet** [comment]
case "NBC":
				path = '/tv/tune?major=11&minor=1';
            
			break

Try this
B

**Comment by bklavet** [comment]
Sweet!
