### ISSUE TITLE
Skill not working 

### ISSUE THREAD

**Issue by Falconeddy** [bklavet/Echo-skill-to-control-Directv#17]
Hi, 

I am able to control the directv box from both my local ip and my wan ip. When I test from the Alexa developer portal, I get the endpoint error. When I test from Lamba, I get an error that it can't load a var/use/index file. I have set it up 3 times but still can't get it to work. Can you help ?

**Comment by bklavet** [comment]
sounds like the trouble is with the zip file you uploaded to aws lambda.  the zip file should contain the Alexa skill file and the updated Index file that can be found in the Custom Slot Skill folder.  the Index file will need to me modified on line 8 with your wan IP, and line 17 with the app id that you get from the alexa developer site.

**Comment by Falconeddy** [comment]
Thanks !

I will check it. I thought I had it right ! Thanks for your help !

Cool app !

Thank you,

**Comment by Falconeddy** [comment]
I have attached the zip file. Still can't figure out what I am doing wrong.

Thanks for your help

Tom

**Comment by vmweaver** [comment]
Tom,
  Did you configure the Lambda Endpoint with its ARN in the AWS Developer
site for your skill?

So APP ID goes in index file, and ARN for Lambda goes on developer site
config for the app.

-- Mark

**Comment by Falconeddy** [comment]
Yes, I did. Does the zip file look ok to you ?

Thanks Mark

**Comment by bklavet** [comment]
Tom, Sent you an email, I checked the zip file and it looks correct to me, but I am going to remove it from this thread so people can't start messing with it.

**Comment by bklavet** [comment]
If you want, I can throw the zip into a lambda function and see if I can get it to work.  then we can hash out what's up with the skill.  What do you think?

**Comment by vmweaver** [comment]
Looks okay.  You should be careful when you go to test in the Lambda
console since it just throws default info into the "Test Event" and will
not work unless you set it up.

What does your "Test Event" configuration look like in Lambda?

You may be able to get more info looking at the Monitoring tab on the
Lambda service. This should give you an option to open in "View Log in
Cloud Watch".  Any more verbose info here?

**Comment by Falconeddy** [comment]
Did you test it ? My receiver did go to CNN. Everything looks like it is right.

**Comment by bklavet** [comment]
yea, I built a test skill and used your wanip. So the skill will work, we just have to figure out what is wrong with your setup.  when you type in "cnn" on the alexa developer test site... what is the response in the box below?

**Comment by Falconeddy** [comment]
I still get the remote endpoint error. Maybe my setup with Amazon is blocking something? It worked for your test.

**Comment by bklavet** [comment]
There is a lot of stuff you have right.  
We know the port is forwarded, and the directv receiver is doing what its supposed to, I can make your zip file work.
send me an email and lets get this sorted out.

**Comment by bklavet** [comment]
Falconeddy rebuilt your aws lambda function and linked to your skill.  passed the tests and should be working
