### ISSUE TITLE
AWS test operating my directv but when i talk to alexa or tell alexa to discover my directv receiver, she says i have no directv device....

### ISSUE THREAD

**Issue by mrchadwk** [bklavet/Echo-skill-to-control-Directv#19]

**Comment by bklavet** [comment]
This skill doesn't discover your directv receiver.  You port forward port 8080 to your directv's IP address.  The aws lambda function points to your wan and fires off the directv commands.  If you can control your directv from the alexa developer portal service simulator.  Alexa will respond to the same commands.  
 if your test is "pause" and it pauses your directv.  you can now say to alexa using the invocation name that you choose something like 
"Alexa, tell [invocation name] to press pause"... and it should pause.  No need to discover cause you have already port forwarded 8080 and the function is pointed to your WAN.  Also there is no need to publish this either you can leave this as is, at this point and it will work.  

Hope that helps
B
