### ISSUE TITLE
Can't control directv with Alexa

### ISSUE THREAD

**Issue by drnorth56** [bklavet/Echo-skill-to-control-Directv#22]
So the message I get when I test any command to directv on the Amazon Developer console I get the following message: The remote endpoint could not be called, or the response it returned was invalid. I went back to my router and made sure the port forwarding was set to 8080 for the Genie (Main directv hddvr for the household) plus I enabled DMV. Either I received the above error message or the response of: I don't understand. I have read some of the input on the chat board but couldn't find the answer....or at least understand it. Thanks for any help you can give!

**Comment by bklavet** [comment]
Hey Dan!  
So first thing we want to do is test that you have port 8080 opened up and that your receiver is enabled to be controlled by third parties.
on the same network as your directv receiver, open a browser and enter this ,but be sure to edit it with your local IP address.
http://192.168.0.2:8080/info/getLocations
you should see a json response as to what you have for receivers.
this means the receiver is going to be able to work with the skill.
next use the same command, but this time edited with the WAN IP address, and from a network that is not on your home network so like your smart phone network like Verizon, AT&t, Sprint,etc.
If you get your receiver info then the port forwarding is working and your ISP is not blocking.

Lets get this verified and then go from there.

**Comment by tonyspinners** [comment]
When you say:
"on the same network as your directv receiver, open a browser and enter this ,but be sure to edit it with your local IP address.
http://192.168.0.2:8080/info/getLocations"

Do you mean the ip address for the receiver, or ip address for your network?

I get nothing when I put in my local ip for the network, but get:

{
  "locations": [{
    "clientAddr": "0",
    "locationName": "GENIE",
    "tunerBond": true
  }],
  "status": {
    "code": 200,
    "commandResult": 0,
    "msg": "OK.",
    "query": "/info/getLocations"
  }
}

when I plug in the ip address for my receiver. Is that correct?


Also, when I login to that getLocations link you posted, using my wan, it takes me to a site that requires a login and has the name of my apartment building. Does that mean there's no where to get through without their approval?

**Comment by bklavet** [comment]
tony!

The wan IP or network IP would be used from an outside network. 
In the above example if you port forward port 8080 on the local ip address 192.168.0.2...

Then http://[wan IP]:8080/info/getLocations should get you this aswell
{
"locations": [{
"clientAddr": "0",
"locationName": "GENIE",
"tunerBond": true
}],
"status": {
"code": 200,
"commandResult": 0,
"msg": "OK.",
"query": "/info/getLocations"
}
}
but port 8080 has to be forwarded to the directv receivers IP.
in this response it shows that you have 1 main genie named GENIE.  the client address for the main Genie is "0" but if you had mini genies hooked up you would see their names and instead of a "0" you would have a MAC address.
another fun one is 
http://192.168.0.2:8080/info/getOptions

**Comment by tonyspinners** [comment]
Thank you very much for the reply. However, while I have you, can you give me feedback on something else?

I was looking around, and NO MATTER WHAT I DID, I could not open my port to my WAN network (If that makes sense). I could connect locally (LAN), but not online (WAN), as many other users have experienced. After looking it up, I found that there's no way for me to open the port as I'm in an apartment complex, where you plug a router into the wall that (I assume) must connect to ANOTHER router from the apartment building (This is evident as my router has a local ip address, a "192." address). Is there ANYWAY around this? Seems from what I've read, there's no way around this without getting direct access to the apartment buildings router (Which of course I can't do).

Hopefully I'm explaining this right, as I've just learned about port forwarding today.

**Comment by bklavet** [comment]
Hmm.  If you are unable to port forward 8080 then the next option isn't as slick as but works.  I would get a raspberry pi and load armzilla's emulator
https://github.com/armzilla/amazon-echo-ha-bridge
this allows the rpi to create a bunch of fake light switches that the echo can turn off and on.  The trick is to assign the directv commands to the fake light switches.  the end result works but takes a lot of typing.
the command structure is "alexa turn on/off pause,play,menu,etc.

**Comment by tonyspinners** [comment]
Man, that's an absolute buzzkill, was hoping there'd be an easier/faster workaround. Thank you anyways, really appreciate the swift and insightful replies

**Comment by bklavet** [comment]
the armzilla is not a bad setup... I was using it before I got help to get this working.  the rpi can be anywhere on the local network, and I was fun getting it going.  the armzilla GitHub is really good at showing what needs to be done.  If you want to go that route, I could maybe give you a hand if you got stuck.

**Comment by tonyspinners** [comment]
Ok, I will give that a try, it'd be good exeprience as I'm actually hoping to learn programming (I'm a complete beginner) to get into that type of career. However, before I let you go. Can you please confirm that when I said I think my router is "second in line" to the buildings router, that that's actually true based off the attached picture (Hopefully I didn't erase too much info)

http://imgur.com/a/3IjPh

Does this picture tell you anything in relation to that?

**Comment by tonyspinners** [comment]
Another question I have (Please forgive me!)



I know the Directv receiver is routed through 8080 in the github files, but can we change that to a port we already know we have access to, then I could change my own router settings to forward my directv receiver to that port as ?

**Comment by bklavet** [comment]
I bet there are no ports open if this is a shared communal network.  Your going to have to buddy up with the apartment manager and see what they can do, or get your own, but I would buy a rpi personally.

**Comment by tonyspinners** [comment]
Will do. I'll message you in the future when I get one if I need any help. Thanks again.

**Comment by drnorth56** [comment]
So this is what I entere
So I put in the command that you told me about editing it with my local ip address and each time I got a message saying that it timed out and couldn't be reached. Sorry I haven't been in touch but I haven't had the time to get back to this. Our tv is our computer monitor and my wife has been home so I haven't been able to spend the time on this. Thanks for your patience.
Dan

**Comment by bklavet** [comment]
Ok, so you will want to double check the receiver.  Verify the IP address that it is using is what you are placing in the http://192.168.0.2:8080/info/getLocations
Then  on the directv receiver under setting and network connections….or something like that, see if you are set to automatic and not manual.  If you are set to manual, note the STB port it is giving and change it to auto.

Next verify this
Make sure the receiver is set to allow SHEF to work.
"In order to use SHEF in your network, it must be enabled in the set-top box by navigating to the “External Device” settings screen (Menu->System Setup->Whole-Home->External Device) screen. Once on this screen select 'Allow' for 'External Access''
more about SHEF can be found here:
http://www.sbcatest.com/TechUpdates/DTV-MD-0359-DIRECTV%20SHEF%20Public%20Beta%20Command%20Set-V1.0.pdf

When you are able to put this link in your home network and get a response then you will next want to port forward 8080.  This has been a snag for people just getting started.  If it does not seem straight forward.  Google your router and port forwarding port 80 or 8080 and you will hopefully find help.  If your directv IP is 192.168.0.2  you would port forward 192.168.0.2 to port 8080 tcp.  This opens up that port to the outside world and everything that comes through it will be directed to 192.168.0.2.

When 8080 is forwarded you should then be able to do this from another network like your smartphone network, or the library, or mall.  Substitute wan ip for your wan IP.
http://wanip:8080/info/getLocations
if you get a response you have the forwarding correct and the skill can start being tested.  So… a little homework there, let me know if you get hung up in the weeds.
B

**Comment by drnorth56** [comment]
Once again thank you for your patience. i'm a little confused. When i do a google search for a local wan ip it says it is: Your Current Public IP Address is: 23.252.85.xxxMade sure all the settings on Directv were set as instructed but I found the address was: 192.168.1.25
Went back to my router which is a asus RT-AC87U and it was set to 192.168.1.25 and port forwarded to 8080. This is the complete setting:
    

|  |  |  |  |  |
| DIRECTV-HR44-C53C397E | 8080 | 192.168.1.25 | 8080       TCP


 |


Anyway, it didn't work and the skill didn't show up in the list of skills for Alexa. Sorry for my lack of knowledge in this area.
Dan

**Comment by bklavet** [comment]
hey Dan,

Ok, open your browser and put the link below in it.
http://192.168.1.25:8080/info/getLocations
your wan Ip is what aws lambda needs to get into your receiver.  Port  8080 is the port directv wants to get it’s info commands on.  So by forwarding port 8080 on the ip of 192.168.1.25  your router knows that if something comes into it from the outside on port 8080, it needs to direct that to your receiver.

Click the above link and cut and paste your response you get…. thanks

**Comment by bklavet** [comment]
I tried your wan ip and was unable to pull the getLocations so 
1: you may not be port forwarding 8080 to 192.168.1.25... or
2: the DTV receiver may not be set up to work yet. (the above link in the last post will rule this out)

**Comment by drnorth56** [comment]
{
  "locations": [
    {
      "clientAddr": "0",
      "locationName": "HDDVR"
    },
    {
      "clientAddr": "CC03FA264F0B",
      "locationName": "HD1"
    }
  ],
  "status": {
    "code": 200,
    "commandResult": 0,
    "msg": "OK.",
    "query": "/info/getLocations"
  }
}

**Comment by bklavet** [comment]
Outstanding Dan! 
that means your receiver is set up correctly.  
now we need to put 192.168.1.25 port forwarded to 8080 in the router, or place 192.168.1.25 in the dmz is that is an option either way should work.

**Comment by drnorth56** [comment]
Okay, changed it in the DMZ. Do I need to make a change now in Lamda?

**Comment by bklavet** [comment]
so now what you would want to do is try the same command but substitute your wan ip for the 192.168.1.25  from a network other than your DTV's network.
http://wan_ip:8080/info/getLocations
if you get the same response as you did on your local network, you can test the skill.  the Index file will need the current wan ip address in it.  
I suggest doing the  getLocations command from a seperate network, cause people have had trouble pulling this off.  It is a good step to do and to know.

**Comment by drnorth56** [comment]
Thanks! I'm about to walk the dogs which is near Home Depot. I will try it on their network and then let you know. Can't thank you enough.
Dan

**Comment by bklavet** [comment]
just make sure you have the current wan ip, If it doesn't work.  then that will need to be addressed.
good luck!

**Comment by drnorth56** [comment]
So I used the address you gave me below thru home depots network and this is what I got:
This site can’t be reached

wan_ip’s server DNS address could not be found.



On January 5, 2017, at 11:03 AM, B money <notifications@github.com> wrote:

so now what you would want to do is try the same command but substitute your wan ip for the 192.168.1.25 from a network other than your DTV's network.
http://wan_ip:8080/info/getLocations
if you get the same response as you did on your local network, you can test the skill. the Index file will need the current wan ip address in it.
I suggest doing the getLocations command from a seperate network, cause people have had trouble pulling this off. It is a good step to do and to know.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bklavet/Echo-skill-to-control-Directv","title":"bklavet/Echo-skill-to-control-Directv","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bklavet/Echo-skill-to-control-Directv"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bklavet in #22: so now what you would want to do is try the same command but substitute your wan ip for the 192.168.1.25 from a network other than your DTV's network.\r\nhttp://wan_ip:8080/info/getLocations\r\nif you get the same response as you did on your local network, you can test the skill. the Index file will need the current wan ip address in it. \r\nI suggest doing the getLocations command from a seperate network, cause people have had trouble pulling this off. It is a good step to do and to know. "}],"action":{"name":"View Issue","url":"https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270728416"}}}

**Comment by bklavet** [comment]
Dan, that means that 192.168.1.25 is not in the dmz 
or...
your isp is blocking traffic on 8080.
what kind of router brand and model are you using?
until you are able to get that command to give the response you received while inside your home network, the skill will be unable to reach your dtv receiver.

**Comment by drnorth56** [comment]
Asus rt-ac87u

On January 5, 2017, at 1:29 PM, B money <notifications@github.com> wrote:

Dan, that means that 192.168.1.25 is not in the dmz
or...
your isp is blocking traffic on 8080.
what kind of router brand and model are you using?
until you are able to get that command to give the response you received while inside your home network, the skill will be unable to reach your dtv receiver.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bklavet/Echo-skill-to-control-Directv","title":"bklavet/Echo-skill-to-control-Directv","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv">https://github.com/bklavet/Echo-skill-to-control-Directv</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bklavet in #22: Dan, that means that <a href="http://192.168.1.25">192.168.1.25</a> is not in the dmz \r\nor...\r\nyour isp is blocking traffic on 8080.\r\nwhat kind of router brand and model are you using?\r\nuntil you are able to get that command to give the response you received while inside your home network, the skill will be unable to reach your dtv receiver."}],"action":{"name":"View Issue","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270762826">https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270762826</a>"}}}

**Comment by bklavet** [comment]
https://portforward.com/asus/rt-ac87u/
check this out these are the ports for xbox live but shows the general idea of where to go.  you would want to do port 8080

**Comment by drnorth56** [comment]
So do I use the same name each time or does it need to be unique? Also at the top right hand corner there is a ! message saying: The wan IP is not the external IP. Eternal IP based services will not work....and it wants me to change it. Not sure how.

**Comment by drnorth56** [comment]
Okay on my way home to check.

On January 5, 2017, at 1:29 PM, B money <notifications@github.com> wrote:

Dan, that means that 192.168.1.25 is not in the dmz
or...
your isp is blocking traffic on 8080.
what kind of router brand and model are you using?
until you are able to get that command to give the response you received while inside your home network, the skill will be unable to reach your dtv receiver.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bklavet/Echo-skill-to-control-Directv","title":"bklavet/Echo-skill-to-control-Directv","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv">https://github.com/bklavet/Echo-skill-to-control-Directv</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bklavet in #22: Dan, that means that <a href="http://192.168.1.25">192.168.1.25</a> is not in the dmz \r\nor...\r\nyour isp is blocking traffic on 8080.\r\nwhat kind of router brand and model are you using?\r\nuntil you are able to get that command to give the response you received while inside your home network, the skill will be unable to reach your dtv receiver."}],"action":{"name":"View Issue","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270762826">https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270762826</a>"}}}

**Comment by drnorth56** [comment]
So here are some screen shots from the router

**Comment by bklavet** [comment]
Found this video that shows a little more.
https://www.youtube.com/watch?v=n98PqITjAC4
For  the famous server list I saw HTTP.  I think that would be a good one to choose and see if it doesn’t throw 8080 in there.
Email  me your wan bklavet@gmail.com<mailto:bklavet@gmail.com>
So  you don’’’t have to go to home depot everytime…. Sooner  or later they will think your shoplifting!

**Comment by drnorth56** [comment]
Sorry, wasn't tracking. This is what I am using and it is trying to find it:
http://23.252.85.197:8080/info/getLocations

On January 5, 2017, at 11:16 AM, B money <notifications@github.com> wrote:

just make sure you have the current wan ip, If it doesn't work. then that will need to be addressed.
good luck!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bklavet/Echo-skill-to-control-Directv","title":"bklavet/Echo-skill-to-control-Directv","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv">https://github.com/bklavet/Echo-skill-to-control-Directv</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bklavet in #22: just make sure you have the current wan ip, If it doesn't work. then that will need to be addressed.\r\ngood luck!"}],"action":{"name":"View Issue","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270731573">https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270731573</a>"}}}

**Comment by drnorth56** [comment]
So the first time i tried it it gave an error message saying the network had changed and it couildn't connect. The second time it timed out.

On January 5, 2017, at 11:16 AM, B money <notifications@github.com> wrote:

just make sure you have the current wan ip, If it doesn't work. then that will need to be addressed.
good luck!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bklavet/Echo-skill-to-control-Directv","title":"bklavet/Echo-skill-to-control-Directv","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv">https://github.com/bklavet/Echo-skill-to-control-Directv</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bklavet in #22: just make sure you have the current wan ip, If it doesn't work. then that will need to be addressed.\r\ngood luck!"}],"action":{"name":"View Issue","url":"<a href="https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270731573">https://github.com/bklavet/Echo-skill-to-control-Directv/issues/22#issuecomment-270731573</a>"}}}

**Comment by drnorth56** [comment]
When I try to put http in the famous server list I get a message that says that it's already been in the list.
