### ISSUE TITLE
Lambda Function Error

### ISSUE THREAD

**Issue by Ebrooks06** [bklavet/Echo-skill-to-control-Directv#25]
I noticed on the AWS Lambda page where I upload the zip file that I'm getting this message, "Your Lambda function "Directv_Control" cannot be edited inline since the file name specified in the handler does not match a file name in your deployment package." Any idea on how to correct this issue?﻿

**Comment by bklavet** [comment]
You shouldn't be able to edit in line cause the alexa file and the index have been zipped together.  the handler should say index.handler.

**Comment by Ebrooks06** [comment]
So that is correct then? Is that what you're saying. I also getting this message in a red box above it. 
"JSON.parse: unexpected character at line 3 column 1 of the JSON data". Perhaps that's the real problem. I just noticed it.

**Comment by bklavet** [comment]
Eric, a few questions to get a better idea of where we are at here.
check this out and let me know the following

https://github.com/bklavet/Echo-skill-to-control-Directv/issues/12

1. Before we get too into this, make sure that the receiver is set for outside control.
2. verify that you are able to control the receiver from your home network.
3. verify port 8080 is forwarded and you are able to control the receiver from outside your home network.

If you are unable to control the receiver from outside your lan, the skill will not work.
if you want to remove your app id and wan info, and attach the zip file you are uploading I will take a look. thanks

**Comment by Ebrooks06** [comment]
I was up all night trying to figure out how to forward port my receiver to port 8080. Back on forth on the phone with Directv and Time Warner (internet provider). Early this morning I read that the Time Warner all in 1 modem & router couldn't be port forwarded specifically. Time Warner told me that port 8080 was open and that's all they could do. So I asked them to bridge the modem so it would work only as a modem and them I went and dusted off my Belkin Router, which I know can port forward. The thing is..I don't know how and couldn't find a good video to explain. So what was easier for me to do..is what you did. I DMZed it..and just opened it up. I assigned it the IP address of my receiver. I also went into the Directv receiver to allow for outside control. 

So i think we checked box 1 & 3.  Regarding #2, not so sure. How can I verify I can control from my home network?

**Comment by Ebrooks06** [comment]
Also I just noticed that on the "Configuration" tab in AWS Lambda, I'm getting this message in a red box.

"Can't call method on null"

**Comment by bklavet** [comment]
Eric! wow! glad you got a solution. 
what type of receiver are you wanting to control? the main genie?  mini genie?  all of it?
if you would like you can attach your zip file you are uploading to lambda and I will take a look.

thanks

**Comment by Ebrooks06** [comment]
Attached is the zip file I will be using.

**Comment by bklavet** [comment]
Didn't get it. Want to attach zip and send to
Bklavet@gmail.com
