### ISSUE TITLE
Trouble getting it to work..... Error via Lambda Test Console

### ISSUE THREAD

**Issue by rmrrmr9** [bklavet/Echo-skill-to-control-Directv#30]
followed instructions and i get following error when i run a test via Lambda test button.

{
  "errorMessage": "onLaunch should be overriden by subclass"
}
 
I should note, I also get the error from echo.  I do get a valid response from the service simulator so i'm ruling out a connection issue.

**Comment by rmrrmr9** [comment]
when i try to execute from Echo - Alex recognizes 'Ask' + my invocation name but then does nothing - error in cloudwatch log shows  -  'Unexpected exception onLaunch should be overriden by subclass'

**Comment by bklavet** [comment]
What version of the skill are you attempting to do?

**Comment by vmweaver** [comment]
@rmrrmr9  this seems to have gone stale. Closing.
