### ISSUE TITLE
Genie - Multiple Receivers and coding

### ISSUE THREAD

**Issue by marklytle** [bklavet/Echo-skill-to-control-Directv#32]
Hi Brandon, 

Thanks for your time and tutorial on the Alex/Directv skills. 
I have one of my Genies working but want to add a second and third into the logic, like you did on your youtube demo video.   Alexa tell directv to goto TBS in bedroom.  

Is this done by modifying the Index file and adding an additional dtv_Mac?  or do you create a whole new alexa skill?   or adding to the sample utterances ?   thanks for the guidance!
Mark

**Comment by bklavet** [comment]
I think you have this github confused with another.
