### ISSUE TITLE
how to add movie channels (and others)?! Ideas?

### ISSUE THREAD

**Issue by JCDinPGH** [bklavet/Echo-skill-to-control-Directv#34]
First, this is excellent. I love being able to command my Directv GEnie from my Echo. I am trying to add more channels into the index which seems like it should be obvious but I can't seem to get channels with two words in them, like HBO West, to work at all. I've been trying for 2 days now and I am hoping someone else has had some luck. Ultimately, I'd like to add almost all of the channels so they are all accessible via voice commands but let's start with just one for now. I added 
addToLineup(504, 	"hbo west");
into the index file
and 
hbo west into the Control list slot. When testing with the service simulator, I get
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Sorry, I didn't understand."
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
Every time.
I have tried several all of the following and all get the same error
hbowest
h.b.o. west
HBO WEST
and several others that I just can't remember now.
Anyone have any ideas/suggestions?
If I can something like "HBO West" to work, I think I can add a lot more channels which I will gladly share with all of you.

**Comment by JCDinPGH** [comment]
The only other thing I noticed is when I tried to change the index file for my local channels so 
addToLineup(5,		"NBC", "WRAL", "n.b.c", "w.r.a.l");
became
addToLineup(11,		"NBC", "WPXI", "n.b.c", "w.p.x.i");
but I am unable to change the channel to "WPXI", only "NBC" seems to work.  Others have the "sorry, I don't understand" error.

**Comment by bklavet** [comment]
Hello JCDinPGH!  So what I think you will want to do, is add
NBC, WPXI, n.b.c and w.p.x.i to the Control_List and update on the alexa developer portal.

What happens is alexa hears the channel nbc, and then passes that value to the function on aws lambda that has the index file.

once you add these values to the Control_List you can go the the service simulator and see what alexa is sending off to aws lambda... make sure what alexa is sending is exactly the same in the index file.

for example if alexa is sending NBC to lambda...and your lambda index file has this
addToLineup(11, "nbc");
it wont work.  NBC does not equal nbc.

**Comment by bklavet** [comment]
Just to add a bit more to this,  I added "hbo west" to the Control_List, and then entered "hbo west" in the service simulator.  
alexa now recognizes that "hbo west" needs to be sent to lambda as a Control_List value.
However it passes the value "hbo west" as "HBO west"  so the index file needs to be looking for it the same way alexa is sending it so the index needs to be 
addToLineup([channel number for hbo west],"HBO west");

**Comment by JCDinPGH** [comment]
Excellent. This definitely gives me a place to start. I will work my way though the channel list and build a new control_list and index and post them here once I get them completed.

**Comment by bklavet** [comment]
cool,  If you get hung up and can give me the channel number and the station, I can maybe help further.
good luck

**Comment by JCDinPGH** [comment]
It shouldn't be to hard but will require a lot of trial and error. Know of any way to test multiple phrases at once? I might try putting them all on one continuous line. 

On Mar 12, 2017 11:46 AM, B money <notifications@github.com> wrote:

cool, If you get hung up and can give me the channel number and the station, I can maybe help further.
good luck

**Comment by bklavet** [comment]
you shouldn't have to add phrases. the sample utterances are pretty sufficient.  You are right that there will be some trial and error though.  
first thing I would do, if figure out the channels you want to add, and the network name, or pet name you want to call the channel. 
next would be to update your Control_List and save.
next go to the service simulator add type in just the items you added to the Control_List and test.  
you should see that alexa is sending of that item as a Control_List, take note of what it is sending and 
Finally update your index file to match the Control_List items exactly like how alexa is sending them.

If you want to provide the list of channels and networks, I can help if need be.
Good luck

**Comment by weiljx** [comment]
Yes! I should have updated the Control_List slot Thanks bklavet!

**Comment by JCDinPGH** [comment]
Here are the channels in my index. I've tested most them by name by running them through the service simulator.  You will need to edit your local channels also for NBC,ABC and CBS to match your local stations and numbers.  If you aren't on the East coast, you will want to edit the channels locations with east or west in them. For instance, I have "HBO" and "HBO east" set to 501, but if you are on the west coast, you will probably want to change "HBO" to point to 504 instead. I have verbally tested all of these with Alexa so your mileage may vary. Just remember that the entries in the index file are case sensitive.  The easiest way to verify/test entries is to use the service simulator in lower case. It appears to recognize several keywords like HBO so even if you put "change channel to hbo" in the service simulator, it translates into "change channel to HBO".  Hopefully this will help others.

				// Specify the channel, then the chanel alias you can provide multiple alias by comma delimiting
				addToLineup(11,  "NBC", "wpxi"); 
				addToLineup(19,  "CW"); 
				addToLineup(2,  "CBS", "kdka"); 
				addToLineup(202,  "CNN"); 
				addToLineup(204,  "hln"); 
				addToLineup(205,  "directv sportsmix"); 
				addToLineup(206,  "ESPN"); 
				addToLineup(207,  "ESPN news"); 
				addToLineup(208,  "ESPN you", "ESPN u"); 
				addToLineup(209,  "ESPN 2"); 
				addToLineup(212,  "nfl Network"); 
				addToLineup(213,  "mlb network"); 
				addToLineup(214,  "mav TV"); 
				addToLineup(215,  "nhl Network"); 
				addToLineup(216,  "NBATV", "NBA TV"); 
				addToLineup(217,  "tennis channel", "tennis"); 
				addToLineup(218,  "golf channel", "golf"); 
				addToLineup(219,  "fox sports 1"); 
				addToLineup(220,  "NBC sports network"); 
				addToLineup(221,  "CBS sports network"); 
				addToLineup(223,  "celebrity shopping network"); 
				addToLineup(226,  "liquidation"); 
				addToLineup(228,  "gem Shopping Network"); 
				addToLineup(229,  "hgtv"); 
				addToLineup(230,  "DIY Network"); 
				addToLineup(231,  "food network"); 
				addToLineup(232,  "cooking channel", "the cooking channel"); 
				addToLineup(233,  "gsn"); 
				addToLineup(235,  "esquire network", "esquire"); 
				addToLineup(236,  "e", "entertainment"); 
				addToLineup(237,  "bravo"); 
				addToLineup(238,  "reelz channel", "reelz", "reals"); 
				addToLineup(239,  "audience"); 
				addToLineup(240,  "hsn"); 
				addToLineup(241,  "spike"); 
				addToLineup(242,  "USA network", "USA"); 
				addToLineup(244,  "sci fi", "syfy"); 
				addToLineup(245,  "tnt"); 
				addToLineup(246,  "tru TV", "true TV"); 
				addToLineup(247,  "tbs"); 
				addToLineup(248,  "fx"); 
				addToLineup(249,  "comedy central"); 
				addToLineup(251,  "oxygen"); 
				addToLineup(252,  "lifetime"); 
				addToLineup(253,  "lmn"); 
				addToLineup(254,  "amc"); 
				addToLineup(256,  "tcm"); 
				addToLineup(257,  "chiller"); 
				addToLineup(258,  "fx movie channel"); 
				addToLineup(259,  "fxx"); 
				addToLineup(260,  "we TV"); 
				addToLineup(261,  "discovery Life"); 
				addToLineup(263,  "rocks TV"); 
				addToLineup(264,  "BBC America"); 
				addToLineup(265,  "a and e"); 
				addToLineup(266,  "fyi"); 
				addToLineup(267,  "pivot"); 
				addToLineup(269,  "history"); 
				addToLineup(271,  "H2"); 
				addToLineup(272,  "logo"); 
				addToLineup(273,  "pop"); 
				addToLineup(274,  "ovation"); 
				addToLineup(276,  "national geographic channel", "national geographic"); 
				addToLineup(277,  "travel channel", "travel"); 
				addToLineup(278,  "discovery"); 
				addToLineup(279,  "Oprah Winfrey network", "own"); 
				addToLineup(280,  "tlc"); 
				addToLineup(281,  "Velocity"); 
				addToLineup(282,  "animal planet"); 
				addToLineup(283,  "Nat geo wild"); 
				addToLineup(284,  "science"); 
				addToLineup(285,  "investigation discovery"); 
				addToLineup(286,  "destination America"); 
				addToLineup(287,  "American heroes channel"); 
				addToLineup(289,  "Disney Junior"); 
				addToLineup(290,  "Disney Channel east", "Disney"); 
				addToLineup(291,  "Disney Channel west"); 
				addToLineup(292,  "Disney XD"); 
				addToLineup(293,  "babyfirst TV"); 
				addToLineup(294,  "discovery Family Channel"); 
				addToLineup(295,  "sprout"); 
				addToLineup(296,  "cartoon network east"); 
				addToLineup(297,  "cartoon network west"); 
				addToLineup(298,  "boomerang"); 
				addToLineup(299,  "nick at nite east", "nick at night", "nick at nite"); 
				addToLineup(300,  "nick at nite west", "nick at night west"); 
				addToLineup(301,  "nick junior"); 
				addToLineup(302,  "nicktoons"); 
				addToLineup(303,  "teen nick"); 
				addToLineup(304,  "television land"); 
				addToLineup(304,  "TV land"); 
				addToLineup(305,  "ion television east", "ion television", "ion TV"); 
				addToLineup(306,  "ion television west", "ion TV west"); 
				addToLineup(307,  "wgn America"); 
				addToLineup(308,  "cloo"); 
				addToLineup(308,  "clue"); 
				addToLineup(311,  "freeform"); 
				addToLineup(312,  "hallmark Channel"); 
				addToLineup(313,  "jewelry television"); 
				addToLineup(315,  "qvc plus"); 
				addToLineup(316,  "evine"); 
				addToLineup(317,  "qvc"); 
				addToLineup(324,  "Americas auction network"); 
				addToLineup(326,  "gac", "great American country"); 
				addToLineup(327,  "cmt"); 
				addToLineup(328,  "TV one"); 
				addToLineup(329,  "bet"); 
				addToLineup(330,  "centric"); 
				addToLineup(331,  "MTV"); 
				addToLineup(333,  "MTV 2"); 
				addToLineup(335,  "vh1"); 
				addToLineup(337,  "vh1 classic"); 
				addToLineup(338,  "up"); 
				addToLineup(339,  "fuse"); 
				addToLineup(340,  "axs tv"); 
				addToLineup(341,  "El Rey"); 
				addToLineup(342,  "fusion"); 
				addToLineup(344,  "son life broadcasting network"); 
				addToLineup(345,  "rfd TV"); 
				addToLineup(346,  "BBC world news"); 
				addToLineup(347,  "Al Jazeera America"); 
				addToLineup(348,  "free speech TV"); 
				addToLineup(349,  "newsmax"); 
				addToLineup(350,  "cspan"); 
				addToLineup(351,  "cspan 2"); 
				addToLineup(352,  "NASA TV"); 
				addToLineup(353,  "Bloomberg TV"); 
				addToLineup(354,  "dog TV"); 
				addToLineup(355,  "CNBC"); 
				addToLineup(356,  "MSNBC"); 
				addToLineup(357,  "CNBC world"); 
				addToLineup(359,  "fox business betwork"); 
				addToLineup(360,  "fox news channel"); 
				addToLineup(361,  "Weather nation"); 
				addToLineup(362,  "the weather Channel"); 
				addToLineup(363,  "geb America"); 
				addToLineup(364,  "insp"); 
				addToLineup(365,  "god TV"); 
				addToLineup(366,  "Jewish life television"); 
				addToLineup(367,  "world harvest television", "wht"); 
				addToLineup(368,  "hope channel"); 
				addToLineup(369,  "daystar"); 
				addToLineup(370,  "ewtn"); 
				addToLineup(371,  "church channel"); 
				addToLineup(372,  "trinity broadcasting betwork", "tbn"); 
				addToLineup(373,  "the word network"); 
				addToLineup(374,  "byu TV"); 
				addToLineup(375,  "link TV"); 
				addToLineup(376,  "ctn"); 
				addToLineup(377,  "tct network"); 
				addToLineup(378,  "nrb"); 
				addToLineup(379,  "Uplift"); 
				addToLineup(381,  "aspire"); 
				addToLineup(382,  "comedy TV"); 
				addToLineup(383,  "justice central"); 
				addToLineup(384,  "revolt"); 
				addToLineup(4,  "ABC", "wtae"); 
				addToLineup(402,  "univision east", "univision"); 
				addToLineup(404,  "galavision"); 
				addToLineup(408,  "Unimas"); 
				addToLineup(410,  "NBC universo"); 
				addToLineup(440,  "Vme"); 
				addToLineup(447,  "canal once"); 
				addToLineup(448,  "Enlace"); 
				addToLineup(461,  "hitn TV"); 
				addToLineup(464,  "Univision deportes network"); 
				addToLineup(470,  "Time Warner cable deportes"); 
				addToLineup(501,  "HBO east", "HBO"); 
				addToLineup(502,  "HBO 2 east"); 
				addToLineup(503,  "HBO signature"); 
				addToLineup(504,  "HBO west"); 
				addToLineup(505,  "HBO 2 west"); 
				addToLineup(506,  "HBO comedy"); 
				addToLineup(507,  "HBO family east"); 
				addToLineup(508,  "HBO family west"); 
				addToLineup(509,  "HBO zone"); 
				addToLineup(511,  "HBO Latino"); 
				addToLineup(515,  "cinemax east", "cinemax"); 
				addToLineup(516,  "cinemax west"); 
				addToLineup(517,  "cinemax moremax", "moremax"); 
				addToLineup(519,  "ActionMax east", "ActionMax"); 
				addToLineup(520,  "5 star max", "5 star max east", "five star max"); 
				addToLineup(521,  "moviemax east", "moviemax"); 
				addToLineup(522,  "thrillermax"); 
				addToLineup(523,  "cinemax Latin"); 
				addToLineup(525,  "stars east"); 
				addToLineup(525,  "stars"); 
				addToLineup(526,  "stars west"); 
				addToLineup(527,  "stars kids and family"); 
				addToLineup(528,  "stars comedy"); 
				addToLineup(529,  "stars edge"); 
				addToLineup(53,  "fox"); 
				addToLineup(530,  "stars in black"); 
				addToLineup(531,  "stars cinema"); 
				addToLineup(535,  "encore east", "encore"); 
				addToLineup(536,  "encore west"); 
				addToLineup(537,  "encore classic"); 
				addToLineup(538,  "encore westerns"); 
				addToLineup(539,  "encore suspense"); 
				addToLineup(540,  "encore black"); 
				addToLineup(541,  "encore action"); 
				addToLineup(542,  "encore family"); 
				addToLineup(545,  "showtime east"); 
				addToLineup(545,  "showtime"); 
				addToLineup(546,  "showtime west"); 
				addToLineup(547,  "showtime 2"); 
				addToLineup(548,  "showtime showcase"); 
				addToLineup(549,  "showtime extreme"); 
				addToLineup(550,  "showtime beyond"); 
				addToLineup(551,  "showtime next"); 
				addToLineup(552,  "showtime women"); 
				addToLineup(553,  "the movie channel east", "the movie channel"); 
				addToLineup(554,  "the movie channel west"); 
				addToLineup(555,  "the movie channel extra east", "the movie channel extra"); 
				addToLineup(556,  "flix"); 
				addToLineup(557,  "sundance TV"); 
				addToLineup(564,  "ifc"); 
				addToLineup(565,  "hallmark movies and mysteries"); 
				addToLineup(566,  "hdnet movies"); 
				addToLineup(567,  "mgm", "mgmhd"); 
				addToLineup(568,  "sony movie channel"); 
				addToLineup(569,  "universal"); 
				addToLineup(570,  "smithsonian channel"); 
				addToLineup(571,  "crime and investigation"); 
				addToLineup(572,  "MTV live"); 
				addToLineup(573,  "shorts"); 
				addToLineup(602,  "tvg"); 
				addToLineup(604,  "pursuit Channel", "pursuit"); 
				addToLineup(605,  "sportsman channel", "sportsman"); 
				addToLineup(606,  "outdoor channel"); 
				addToLineup(610,  "btn"); 
				addToLineup(611,  "sec network"); 
				addToLineup(614,  "ESPN classic"); 
				addToLineup(615,  "ESPN bases loaded games only", "ESPN goal line games only", "ESPN buzzer beater games only"); 
				addToLineup(618,  "fox sports 2"); 
				addToLineup(620,  "being sports"); 
				addToLineup(621,  "fox Soccer Plus"); 
				addToLineup(628,  "nesn"); 
				addToLineup(630,  "Comcast sportsnet new England"); 
				addToLineup(631,  "yes network"); 
				addToLineup(634,  "msg"); 
				addToLineup(635,  "msg plus"); 
				addToLineup(639,  "sny"); 
				addToLineup(640,  "masn"); 
				addToLineup(642,  "Comcast sportsnet mid Atlantic"); 
				addToLineup(646,  "fsn south"); 
				addToLineup(649,  "fox sports Southeast"); 
				addToLineup(653,  "fox sports sun"); 
				addToLineup(654,  "fsn Florida"); 
				addToLineup(659,  "root sports Pittsburgh"); 
				addToLineup(660,  "fsn Ohio"); 
				addToLineup(661,  "fsn Cincinnati"); 
				addToLineup(662,  "sportstime Ohio"); 
				addToLineup(663,  "fsn Detroit"); 
				addToLineup(665,  "Comcast sportsnet Chicago"); 
				addToLineup(668,  "fsn north"); 
				addToLineup(671,  "fsn midwest"); 
				addToLineup(674,  "root sports southwest"); 
				addToLineup(676,  "fsn southwest"); 
				addToLineup(677,  "longhorn network"); 
				addToLineup(681,  "altitude sports"); 
				addToLineup(683,  "root sports rocky mountain"); 
				addToLineup(686,  "fsn Arizona"); 
				addToLineup(687,  "root sports northwest"); 
				addToLineup(691,  "Time Warner cable sportsnet"); 
				addToLineup(692,  "fsn west"); 
				addToLineup(693,  "prime ticket"); 
				addToLineup(694,  "fsn San Diego"); 
				addToLineup(696,  "Comcast sportsnet bay area"); 
				addToLineup(698,  "Comcast sportsnet California");

**Comment by JCDinPGH** [comment]
After creating the new entries for index in the previous post, I was able to test some of them later in the day. They still need a lot of work. Stay tuned for updates as it appears I am going to have to test each one individually as the service simulator is only partially helpful. For example, I have no idea how to get a channel like "VH1" to work. Ideas?

**Comment by weiljx** [comment]
Try V.H One Also you may want to add these to your custom slot. It should help Alexa reconize the channel names better

**Comment by JCDinPGH** [comment]
I found it. It's "V h 1". I found if you use Alexa to make a list you can say whatever you want, and then look in the app at your list, and see exactly what she hears. This works much better than the simulator.

**Comment by bklavet** [comment]
JCDinPGH,  You have a pretty extensive line up. :)  I could have swore I had vh1 sorted out with "vh one" as the Control_List value.    If you wouldn't mind doing a post like the one above with what you are happy with, I would like to get the Index and Control_List updated.

Thanks for sharing your findings.  It is appreciated!
