### ISSUE TITLE
 "Unexpected token ILLEGAL",

### ISSUE THREAD

**Issue by Bmiller777** [bklavet/Echo-skill-to-control-Directv#36]
Hi bklavet.
I have external port receiving commands outside of my network, and it seems the lambda function is configured correctly, but these are the errors I am getting in the lambda tests.

  "errorMessage": "Unexpected token ILLEGAL",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Module._compile (module.js:373:25)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

**Comment by bklavet** [comment]
Hello bmiller, what version of the skill that you are putting in?  are you following the "dated" walk through video?

**Comment by Bmiller777** [comment]
Hi Bklavet,
  Thank you for your reply.  I just got it working 20 minutes ago.  It's a great skill.  
What's the difference between the Custom Slot Sklill and the one with Voice Command?

Brian Miller

**Comment by bklavet** [comment]
That's great! The voice guide, allows a person to ask what's on a channel and Alexa will tell you why's current playing on the requested channel, or say what's currently playing.

The custom slot skill lacks the voice guide.  And the custom slot skill for the genie mini, lets you set up skills for the client receivers.

**Comment by oneofayykind** [comment]
I'm getting this same error. How did you fix it?

**Comment by bklavet** [comment]
Hello, what version of the skill are you trying to use? are you testing through the alexa developer site or in lambda?  

Make sure the region you are in is N. Virginia on the lambda side of things.
