### ISSUE TITLE
Commands work periodically with custom slot skill for mini genie

### ISSUE THREAD

**Issue by bigtech12** [bklavet/Echo-skill-to-control-Directv#40]
I believe I have set everything up correctly to get the custom slot skill for the mini genie to work as I can test the command "Echo, tell DirecTV to change to Animal Planet", however, this  only works randomly.  In some cases, Echo responds with there is no device"directv".  It is almost as if there is a communication breakdown.  I was also able to get the DirecTV to pause every once in a while.  Just wondering if you have any troubleshooting suggestions.  Also, thank you for sharing this as it gets me one step closer to automating my home!  Great work!

**Comment by bklavet** [comment]
It is most likely the invocation name directv that is your problem.  Try changing it to "TV" and see if you get better results.
