### ISSUE TITLE
Not working on a wireless Genie Mini

### ISSUE THREAD

**Issue by conpboyle** [bklavet/Echo-skill-to-control-Directv#41]
I'm trying to get this working using a Wireless Genie Mini - At first glance everything appears to be working and Alexa even responds with an "OK" when you speak commands - the problem is that the Genie Mini doesn't respond.

A few of the things I have checked -

I have the index file set up with my local IP, App ID, and the MAC address for Genie Mini that I want to control.
My router is a "ZyXEL VMG4381-B10A." I think I have port forwarding 8080 set up correctly... I also set my main receiver's IP on the DMZ page. (screenshots below, maybe I'm doing this wrong?)
![8080](https://user-images.githubusercontent.com/29679870/27511811-a24d2512-58fb-11e7-9c51-7742f33fff01.png)
![dmz](https://user-images.githubusercontent.com/29679870/27511813-a46ec8fa-58fb-11e7-8eb4-09b907ad0896.png)

I'm getting this error through the Alexa app - "Request Identifier" amzn1.echo-api.request.45784447-2baf-4294-91b8-22f85ece0333 The target Lambda application returned a failure response

**Comment by bklavet** [comment]
Hey there,  I am on the road right now but should be back Sunday.  Can you control the mini genie from your browser?

**Comment by conpboyle** [comment]
Yup! I am able to control the mini genie (channel up, down, etc) from my home network w/ my local IP in the address bar as well as my cell phone (Sprint) network with my WAN IP in the address bar.

**Comment by bklavet** [comment]
You may have your Mac entered wrong in the lambda function index file.

**Comment by conpboyle** [comment]
I tried entering the MAC in the index file again but unfortunately no luck - 
![screen shot 2017-06-25 at 1 13 40 pm](https://user-images.githubusercontent.com/29679870/27518208-5d6f7c80-59a8-11e7-9a5d-61a59df2851a.png)

**Comment by bklavet** [comment]
var dtv_Mac = '&clientAddr=D0B2C45F24F3';
Not sure what version of the skill you are using, but if it is the mini genie skill, the &clientAddr=xxxxxxxx in the variable, you only show the mac.  Double check.

**Comment by conpboyle** [comment]
That was the problem!  It's working great now - Thank you very much for your help with this!

**Comment by bklavet** [comment]
Outstanding!
