### ISSUE TITLE
WAN

### ISSUE THREAD

**Issue by erinnire5** [bklavet/Echo-skill-to-control-Directv#42]
Hi. I am very new to Alexa skills so pardon me if this is my ignorance.  I went through the Youtube tutorial and am testing the skills on developer.amazon.com and continue to get the error 'The remote endpoint could not be called, or the response it returned was invalid.' when I enter 'go to cnn'.  I have been trying to troubleshoot.  I ensured the reciever was set to allow external access,  setup port 8080 forwarding on my Netgear Nighthawk, can pause the directv from my LAN but cannot figure out/get it to pause it on the WAN.  I entered this on my cell phone http://2910:6600:1706:k653:7f89:8678:n988:g82g:8080/remote/processKey?key=pause&hold=keyPress (I changed characters for security).  I entered with both colons and without.  What am I missing?  Thereceiver model is HR44/500 so I dont believe its a mini genie.

**Comment by vmweaver** [comment]
So it looks like you have an IPv6 address.....
Sometimes IPv6 addresses need to have square brackets around them "[" and
"]" followed by  colon ":" then the port number 8080.

so:  
http://[2910:6600:1706:k653:7f89:8678:n988:g82g]:8080/remote/processKey?key=pause&hold=keyPress

**Comment by erinnire5** [comment]
Thanks for the quick response.  I attempted with the brackets and still get an error page.  Any other ideas?

**Comment by erinnire5** [comment]
I was reading about the MAC address and thought id try but where would i get this info from? The router or the directv?

**Comment by vmweaver** [comment]
​If you don't need to use the MAC address when calling internally, you
shouldn't need to specify it with a remote call.
 Some providers will block inbound ports or at least SOME inbound ports..
so there may be some other things outside of your control.
You could TRY to change your port forwarding/triggering config to create
your external listener on port 80 and your internal port will be 8080.
So External Port Range from 80 to 80 and Internal Port Range from 8080 to
8080 and see if that is any better.

Not sure if this will interfere with your router's native web ui, though.

**Comment by vmweaver** [comment]
@erinnire5 - Just following up on this issue. Did you get it figured out?

**Comment by vmweaver** [comment]
I don't believe that Amazon Lambda functions can call to an IPv6 address.  Many ISPs are "dual mode"ing customer customer connections. This means your router would have both and IPv4 and IPv6 addresses.  There are several places that will tell you both, but your mileage may vary.
Try: http://whatismyip.host/
As such I am closing this out and we should be updating the guidance to use IPv4.
