### ISSUE TITLE
Endpoint error 

### ISSUE THREAD

**Issue by DMRBx** [bklavet/Echo-skill-to-control-Directv#43]
I've tried 3 times to set this up (deleting and starting over each time) but I keep receiving an error. "The remote endpoint could not be called, or the response it returned was invalid." The port is open & I can pause the Directv when using my computer & my mobile phone. But for some reason I can't figure out, I keep receiving the error. The index file has all the correct information with my IP (using what's my IP search) and the ID I received from the developer side. I've also uploaded the zip file as shown in the tutorial. I'm completely new at this, but I'm sure I followed the YouTube video posted by B Money. Any help would be greatly appreciated.  *Edited to add, my Directv receiver has also been set to Allow External Access*

**Comment by bklavet** [comment]
Which version of the skill are you attempting to use? The same one I did in the you tube video?

**Comment by DMRBx** [comment]
Yes, custom skill

**Comment by bklavet** [comment]
Sure,  
There are only two places in the index file that need to be modified:
1  the wan IP address
2  the skill ID

Sounds like you have a handle on that.  the index and alexa file needs to be zipped together and uploaded to aws lambda.  Make sure you are set for the N. Virginia location.  This is at the top left of the lambda page.  

Double check that the alexa skills kit as the trigger.
https://youtu.be/hG6cAlO07vw
the above is a link to video on how to setup the lambda stuff... maybe it can help.
