### ISSUE TITLE
Another  "remote endpoint..." error

### ISSUE THREAD

**Issue by nidan2703** [bklavet/Echo-skill-to-control-Directv#45]
I am getting the remote endpoint error other users have detailed.
Double checked that I used the outside IP in the index file and that port is forwarded to 8080. Since that didn't work, I also added the internal IP to the DMZ, however, still no luck.
I tried the http call procedure to try and test pausing the HR44 from an internal device, but even that ends in an error.
I noticed in one of the strings that somebody mentioned to put brackets around an IP v6. Since my external IP is in IP v6 format, should I try to place brackets around the IP in the index file?
Since i cant even successfully complete the http call precedure, any chance I simply have a port issue?

Thanks for any suggestions

**Comment by nidan2703** [comment]
Well, after sleeping on it and messing with it for a while this morning, I tried the http call procedure on various receiver models. None of them worked. Mind you, I had typed the url (big mistake). I then copied and pasted it and voila, the internal IP call worked. However, as soon as I tried the external one, - again, no dice. So I decided to unplug the cable modem in the hopes of pulling an IP v4 on reboot and luckily I did. Once I inserted the (external) IP v4 into the index file, everything works.
So I now have two take away questions from this. HOW do I make it work once I pull another IP v6 or should I ask my ISP to issue me a static IP to prevent this from happening (hopefully they would issue me an IP v4 upon request)?

**Comment by bklavet** [comment]
a static address will keep this from happening or getting a domain name and point the skill to it.  Thanks for sharing your experience with this!

**Comment by nidan2703** [comment]
Quick question if I may? The skill tested just fine and it’s showing activated under the skills section in my Alexa app, but Alexa has no idea what I’m asking for when I try to use it. She replies that she has no device by that name (DirecTV) installed. I apologize in advance if this is user error, I just bought this thing last week 😬
Thanks,Achim Brunette 
		

		Get Outlook for iOS
	_____________________________

**Comment by bklavet** [comment]
I had the same problem with the invocation name directv.  alexa is trying to parse the invocation name into something it believes is a word.  you could try "direct tv" or "tv".  The good news is that the invocation name is one of the easiest things to change and does not require any changes to your aws lambda function.

**Comment by nidan2703** [comment]
Thx, I’ll give that a try 👍🏼
Achim
		

		Get Outlook for iOS
	





On Tue, Aug 1, 2017 at 1:52 PM -0700, "B money" <notifications@github.com> wrote:












I had the same problem with the invocation name directv.  alexa is trying to parse the invocation name into something it believes is a word.  you could try "direct tv" or "tv".  The good news is that the invocation name is one of the easiest things to change and does not require any changes to your aws lambda function.
