### ISSUE TITLE
cannot

### ISSUE THREAD

**Issue by SKSLe** [bklavet/Echo-skill-to-control-Directv#47]
Hi I am trying to connect to genie but does not work here is the error message from my lambda
"The remote endpoint could not be called, or the response it returned was invalid."

I can get the custom slot skill work but not this one for my genie. 

Thank you very much

here is my setting 

var http = require('http'); // if going through a proxy that uses SSL change to "require('https');"

// Your external IP. Alexa can only access publically-accessible IPs. No LAN access unfortunately.
// Make sure to set up port forwarding on port 8080 to your DTV's IP on your router.
// In my case I had to move receiver to DMZ
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var local_ip = ’73.161.XXX.XXX’;
//externalIP or FQDN //////////////////////////////////////////////////////////////////////////
//var local_ip = '<some fqdn>';
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var dtv_Mac = '&clientAddr=00XXXXXXXX’; **All CAPS**
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/**
 * App ID for the skill
 */
 //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var APP_ID = "amzn1.ask.skill.0ef948b8-1002-441c-bb29-XXXXXXXX";

**Comment by bklavet** [comment]
https://github.com/bklavet/Echo-skill-to-control-Directv/issues/12

SKSLe, see the link above and verify that the DTV receiver is set up, and that you can control the DTV receiver from outside your home network to verify that port forwarding has been set up correctly. 

reply back after this is done and we can move on to trouble shooting this further.
