### ISSUE TITLE
Im stuck at this point

### ISSUE THREAD

**Issue by wwwgizy** [bklavet/Echo-skill-to-control-Directv#51]
<img width="1470" alt="screen shot 2017-08-28 at 8 04 34 pm" src="https://user-images.githubusercontent.com/31396906/29798665-60a36ee6-8c2c-11e7-92d5-ca5dba3a49c5.png">

Does this seem all good ? if so whats next i did try telling alexa commands and nothing?

**Comment by wwwgizy** [comment]
Does this seem all good

**Comment by wwwgizy** [comment]
im trying to get it to with directv mini mostly

**Comment by bklavet** [comment]
https://github.com/bklavet/Echo-skill-to-control-Directv/issues/12

**Comment by bklavet** [comment]
see if you can control your receiver from the browser, and then try to control it from outside the network your lan is on, refer to the link above for help.

let me know if you can do this.

**Comment by wwwgizy** [comment]
How can I control from browser?

**Comment by bklavet** [comment]
wwwgizy,
port forwarding 8080! So, this needs to be done in the router, or firewall. each users setup will vary if port 8080 is not forwarded the skill will fail. To help trouble shoot if port 8080 is forwarded do this:
a. Make sure you can control your receiver from within your lan. This allows you to know the receiver is set up to receive commands and can be controlled locally. Do this by finding out what IP your receiver has been assigned (10.0.1.xx, 192.168.0.xx,etc.) using the local IP alter this pause command to match your local IP.
pause command
http://[local_ip]:8080/remote/processKey?key=pause&hold=keyPress
place this command in a browser window of a computer on your local network and hit enter. The directv receiver should pause.
next try to pause the receiver from outside your local network. alter the pause command to match your wan ip address. then open a browser and place this command and hit enter. Keep in mind this needs to be on a different network so from a cell phone or friends house.
http://[wan_ip]:8080/remote/processKey?key=pause&hold=keyPress
if the receiver pauses you have port 8080 forwarded and your ISP is not blocking port 8080.

**Comment by wwwgizy** [comment]
I did get it working thanks

**Comment by wwwgizy** [comment]
question do I need to say" ask directv channel number each time? Or can this be changed to say just. “Directv channel” if so how?
Thanks

**Comment by bklavet** [comment]
glad you got it working.  The utterances can be modified to accommodate how you speak, but you will always need to start with "Alexa, (tell/ask/etc) [invocation name].....  
If it detects a number it should flow to the channel slot,  So I think a person could say:
Alexa, tell [invocation] two oh two.
