### ISSUE TITLE
Alexa says "I couldn't find any linked video skills that can do that"

### ISSUE THREAD

**Issue by sdoxley** [bklavet/Echo-skill-to-control-Directv#55]
I've gone through the setup twice and testing with the Service Simulator works fine, i.e. when i type in "go to CNN" it will change the channel so that tells me port forwarding is working.  However, when I ask Alexa, tell directtv go to CNN she reports this error.  I even get this error when using the Test Simulator.  Any suggestion on resolving this?

**Comment by bklavet** [comment]
It is the invocation name. Try "direct TV" or "TV", and see if you get better results.  The good news is the invocation is easy to change and you wont need to redo anything with the lambda function.

**Comment by sdoxley** [comment]
That worked!  I guess Alexa doesn't understand "directtv" or "directv", but understands "direct tv"

**Comment by bklavet** [comment]
you got it!  Alexa is just crunching the words it hears and tries to associate them to something it believes are "real words". when you have directv as the invocation, it will have a hard time.  Thanks for letting me know you got it going!  That is Awesome!
