### ISSUE TITLE
Issue with Power On/Off with Mini

### ISSUE THREAD

**Issue by Rob-stark** [bklavet/Echo-skill-to-control-Directv#57]
Just got an Echo for Christmas and found this right away.  Awesome job.  I can get the main DVR to power on and off but doesn't work on the mini. "Alexa, ask television power": Alexa comes back and says 'ok' but it doesn't do anything.   So far everything else seems to be working ok.

**Comment by bklavet** [comment]
people have had different results with the "power".  To get the mini's to work you need to make a skill that has the MAC of the mini in the index.  there is a skill for the mini ... line 12 is where you input the Mac.  If you need help finding the mac, go to issue twelve and check out step four
#12

**Comment by Rob-stark** [comment]
I'm using the skill for the mini.  I've also tried to go directly to the API and run the command for the power and it doesn't work. http://localIP:8080/remote/processKey?key=power&hold=keyPress&clientAddr=MACID  Response comes back with "OK" but still does nothing.  Was just curious if you knew of a fix.  I'll keep playing with it.  Thanks.

**Comment by bklavet** [comment]
the above url (i am assuming you put the mac of the mini in place of the MACID) is for the local network.  If you place that in the browser and it fails to turn on, but something like this....
 http://localIP:8080/remote/processKey?key=pause&hold=keyPress&clientAddr=MACID 
does work.  

what this is saying is that your mini when turned off is turning off the network connection to the main genie.  

My guess is if the mini is on, the power command will turn it off.  That was my experience.

**Comment by vmweaver** [comment]
@Rob-stark Is this still an issue for you? 
If no response we will close in 2 days.
