### ISSUE TITLE
"I didn't understand"

### ISSUE THREAD

**Issue by aaronfisherIT** [bklavet/Echo-skill-to-control-Directv#58]
In the simulator, changing to certain channels returns a response of "I didn't understand"
"c span"
"Disney xD" (listed as "disney x.d." but that is not understood either)
"vh 1"  ( this works with "vh one" but is listed as "vh 1" in index)

![image](https://user-images.githubusercontent.com/35021439/34475194-517379f8-ef4f-11e7-992e-532337bce55f.png)

**Comment by aaronfisherIT** [comment]
This might just be a simulator issue. . . uttering "turn to c span" does actually work.
![image](https://user-images.githubusercontent.com/35021439/34475226-b4322350-ef4f-11e7-9274-8b38ff04bb8a.png)

**Comment by bklavet** [comment]
Hello!

so if we put in c. span it sends off to the index "C span"
"slots": {
        "Control": {
          "name": "Control",
          "value": "C span"
        },

the index currently shows c span as this:
case "c span":
path = '/tv/tune?major=250';
break;
So, C span needs to be updated in the index to this
case "C span":
path = '/tv/tune?major=250';
break;

in the control list values, it may not hurt to edit c span to c. span aswell

**Comment by bklavet** [comment]
your second screen shot shows Disney xd, is this another channel that is not responding?

**Comment by aaronfisherIT** [comment]
I had the same problem with c span, Disney xd, and vh 1   BUT.....
I think this is just a problem with the input on the simulator,  reason being that all three controls respond correctly if the input is changed to "turn to c span" or "turn to disney xd" they just don't work by themselves like the rest of the channels do.

**Comment by aaronfisherIT** [comment]
Although I don't understand why saying "Turn to c span" gets this:
 "Control": {
          "name": "Control",
          "value": "c span"
        },
  "Channel": {
          "name": "Channel"

but just putting in "c span" gets no value : 
Control": {
          "name": "Control"
        },
        "Channel": {
          "name": "Channel"

because when you put in a different channel, like just "fox"
it returns a value of "fox"
  "Control": {
          "name": "Control",
          "value": "fox"
        },
        "Channel": {
          "name": "Channel"

**Comment by bklavet** [comment]
ah!!! so what is happening is it is grabbing the sample utterance turn to {Control}, and then runs it through the Control_List.

to have better success with this network the index should/could look like this
case "C span":
case "c span":
path = '/tv/tune?major=250';
break;

this gets all the bases covered.

I don't show any issue with Disney xd.

**Comment by bklavet** [comment]
of course it is a slippery slope with something like c span
lots of ways for alexa to interpret it..
sea span
see span
C span
Si Span

:)

**Comment by aaronfisherIT** [comment]
HAHA So really the programming of it is irrelevant because she's going to misunderstand 30% of the time anyway? I think you have a point.

**Comment by aaronfisherIT** [comment]
This may be a stupid question, but I can't test it, and the developer console says "  Enabled  This skill is enabled for testing on your account. "

The amazon account tied to the echo doesn't matter for the enabling of this skill, right? As long as i'm pointed to the right public IP for a network with anybody's alexa and a directv (port forwarded) , she should now be able to run these commands, even without enabling anything in the alexa app. 
Is that correct?

**Comment by bklavet** [comment]
I will circle back to vh1 that was originally v.h. one but the alexa started sending it as the way it is currently,  I will see if I can see how alexa is sending it now and will update.

**Comment by bklavet** [comment]
the account does matter,  the account you use to make the skill needs to be the account the alexa device is signed into.

**Comment by aaronfisherIT** [comment]
awww man. . . there goes my big reveal :(

**Comment by aaronfisherIT** [comment]
Thanks for all your help, this skill is awesome! 👍

**Comment by bklavet** [comment]
sure thing
