### ISSUE TITLE
Error Issue on trying to save Alexa Skills

### ISSUE THREAD

**Issue by StarfighterJ** [bklavet/Echo-skill-to-control-Directv#60]
HI I am getting a error just trying to Save the Alexa Skill kit See Attached:
Did I get a bad Download?
![2018-01-04](https://user-images.githubusercontent.com/29153197/34585839-7ad4ba6a-f16f-11e7-9e4a-5f41052cb507.png)

**Comment by bklavet** [comment]
What do you have for your schema?

**Comment by bklavet** [comment]
Also you have to hit the add button on the custom list values

**Comment by StarfighterJ** [comment]
Thanks bklavet I missed the Add step in the Video on custom list values

**Comment by bklavet** [comment]
no problem!
