### ISSUE TITLE
var APP_ID in Index Question

### ISSUE THREAD

**Issue by StarfighterJ** [bklavet/Echo-skill-to-control-Directv#64]
bklavet First thanks for the History on you Hobby on getting this to work. I am a old timer programmer LOL talking about key punch Card days Basic, Dbase and Clipper. Trying to learn JSON..
I looked at your Future JSON Index. is this a attempt to get the var App_ID to self populate? If not is there any thought of the Program doing this instead of coping and Pasting it in? One more question on the var App_ID Why is it required to be in the index file?

Additional Question on future JSON is There a Attempt to be able to User input the WAN IP before the Alexa Skill is Enabled?

**Comment by vmweaver** [comment]
I think the attempt in the "future" folder is to parse the Alexa response
so that she can tell you what you are currently watching.  Kind of like
getting "info" on the screen and have her read it to you.
The App_ID in the Index file is a requirement for the Amazon Lambda
service, I believe.

**Comment by bklavet** [comment]
the future folder was a place to stick the stuff that didn't work. 

In all honesty i haven't looked at it for about a year, and should probably get rid of all the stuff that may take someone off the rails.

a cool direction to go in my opinion would be to have the skill be able to update the aws lambda wan address for everyone who do not have static wans.  this way if the wan changed, and the skill stops working a user could verify what the wan is in the aws lambda function, and then be asked if the wan should be updated and allow the user to update the wan variable.
