### ISSUE TITLE
Custom Slot Skill with Voice Guide - syntax errors

### ISSUE THREAD

**Issue by vmweaver** [bklavet/Echo-skill-to-control-Directv#66]
@weiljx I have spent some time trying to hack through your code (very nice by the way) since I was plagued by syntax errors and such.  Were you able to get it to work?

I have managed to get something to work that also incorporates the "secure" connection thing I was working on.

My wife is watching a Wuthering Heights right now, so I don't DARE go try to change channels on her. ;-)

I will let you know how my testing goes.  Being a bit of an arm-chair developer, I learned a lot from going through your code.

**Comment by weiljx** [comment]
@mawrew I have it working and it was merged into the main repo from bklavet. I started making some changes around Christmas time that I have not fully tested or checked in yet. 

My latest changes are designed to allow you to configure what DirecTV packages you have and potentially allow you to control multiple gini minis from a single instance of the skill. I have also gone through the utterances and slots to try and make the skill even more responsive. All so it is easier for my father in law to work.

When the new code is ready I will be sure to get it checked in but what's up now should work as well.

Josh

**Comment by vmweaver** [comment]
Ah.. I know what my issue was (just recalling what I went through).  I failed to include the modules folder and you are using the "request" module to get the current program.    Can disregard this, but I would like to include some of the tweaks I did. 
Thanks for your work on this.

**Comment by vmweaver** [comment]
Probably need to update the README to include adding that folder to the ZIP you upload..
