### ISSUE TITLE
Seems to be working, but nothing happens

### ISSUE THREAD

**Issue by reedh11** [bklavet/Echo-skill-to-control-Directv#67]
The skill tested fine, alexa responds ok to command, but nothing happens.  I have verified port 8080 is open.  If I am far from my router will that make it not work?

Only other thing I don't understand is when I modified the index, I used the IP address that it gave me when I did the google search downstairs, when I am upstairs where the echo dot is, I get a different IPv6 address.  Would this be causing an issue?

You're a genius, thanks for posting this.

**Comment by bklavet** [comment]
is this a main genie or a mini?
what version of the skill are you using?
have you veerified #12 ?
Oh and Hi reedh1l!

**Comment by vmweaver** [comment]
Distance from router shouldn't make a difference.  Is it possible that you
are somehow connecting to a neighbor's WIFI automatically? I can't
understand why your external address would change if you are going through
the same router.
I mean your external address CAN change depending on your service provider, but generally they aren't that fast.  Do you consistently get the same addresses in both locations?

**Comment by reedh11** [comment]
I don’t believe that is happening as it’s protected.  In the index file which IP address should I be using?  The IPv4 one or the IPv6 one that I get when I’m upstairs (where the echo dot is). I have tried both, the IPv6 version failed at testing, saying something about end point.

Thanks a bunch for your help.





On Jan 9, 2018, at 7:02 PM, mawrew19 <notifications@github.com<mailto:notifications@github.com>> wrote:

Distance from router shouldn't make a difference. Is it possible that you
are somehow connecting to a neighbor's WIFI automatically? I can't
understand why your external address would change if you are going through
the same router.

**Comment by vmweaver** [comment]
This is interesting. So you have a laptop and you go to where one of the
devices is and you google 'what's my ip' and you get an IPv6 address, then
go elsewhere and get an IPv4 address?
Are they always the same IPv6 and IPv4 addresses?
Do you have just a single access point or wireless router?  It *IS*
possible to have both an IPv6 and an IPv4 addresses on the external side.
If you login to your router is there any config that says that both are
enabled?
Do you mind if I ask who your service provider is?

**Comment by vmweaver** [comment]
​Maybe try going to this site: https://test-ipv6.com/

Looks like it may be able to tell you if you have both ipv4 and ipv6​

If you DO have both, then really either one should work regardless of what google "detects".

**Comment by reedh11** [comment]
I was doing it on a phone so maybe that’s the problem. But yes depending where I was I got an IPv4 number downstairs or closer to the router(which never changed). Then upstairs on the phone I got an IPv6 number.  It would change (the first 4 sections of 4 digits was always that the same. The next 4 sections would change.

AT&T is my provider for internet.

On Jan 9, 2018, at 7:28 PM, mawrew19 <notifications@github.com<mailto:notifications@github.com>> wrote:

​Maybe try going to this site: https://test-ipv6.com/

Looks like it may be able to tell you if you have both ipv4 and ipv6​

**Comment by vmweaver** [comment]
Some phones have a mode where they can use both Wifi and Mobile data to
optimize the connection speeds, so I wonder if that's what happening. If
you turn off your Wifi on your phone and get your address, does it match
either the ipv6 or ipv4 addresses?​

**Comment by vmweaver** [comment]
If you have an iPhone, you can check this out:
https://support.apple.com/en-us/HT205296

**Comment by reedh11** [comment]
Ok it was the phone. I just googled it on my laptop upstairs and I get the IPv4 address, which is what is in the skill.



On Jan 9, 2018, at 7:55 PM, mawrew19 <notifications@github.com<mailto:notifications@github.com>> wrote:

Some phones have a mode where they can use both Wifi and Mobile data to
optimize the connection speeds, so I wonder if that's what happening. If
you turn off your Wifi on your phone and get your address, does it match
either the ipv6 or ipv4 addresses?​

**Comment by bklavet** [comment]
#12
what do you get with number 3? you your laptop that is on the same network as the dtv
is this a mini or main genie?

**Comment by vmweaver** [comment]
Awesome.  So glad you were able to track that down.
You still have issues with the Skill, though, right?
You said you DID setup Port Trigger or NAT on your router for port 8080 and sending to port 8080 on your DTV box, right?

**Comment by reedh11** [comment]
yes still having problems with the skill.  I am using a genie, and that is the version of the skill I downloaded.  I used can you see me to make sure that port 8080 is open for the main Direct TV receiver, and it shows as open.  I have allowed external devices on the main direct tv receiver.  Sometimes she responds ok and nothing happens, other times she responds "there was a problem with the requested skill response".

**Comment by reedh11** [comment]
i tested number 3, and can pause the main direct tv receiver both ways.  Seems to be the link to the genie that isn't working.

**Comment by bklavet** [comment]
hello reedh11,
number three is a big one! and the fact you can pause the tv with the wan ip is huge.
so, if you go to the service simulator on the developer console and submit pause, what is the response you get back on the response screen?

are you using the same version as the you tube video?

Thanks

**Comment by reedh11** [comment]
I get ok.  no errors.  I am using the version that says custom slot skill for mini genie.

**Comment by bklavet** [comment]
if you are going to use that version to control your main receiver you need to change this line to look like this in the index file
&clientAddr=XXXXXXXXXXX
&clientAddr=0
the skill is sending XXXXXXXXXX as a mac and the main genie doesn't know what to do with it.

**Comment by reedh11** [comment]
Just to be clear, do I have to set up a skill for both? (one for main receiver, and one with the genie MAC #).

Or do I just modify the current skill (for Genie) as you have above?

Thanks again.

**Comment by bklavet** [comment]
for the main genie you can use :
Custom Slot Skill
or the Custom Slot Skill with voice guide

the one that you probably wouldn't want to use for the main Genie is the one that says for mini genie,
but with the changes above, it should work too.

If you want to get the mini genie going check number 4 on this issue #12 verify the mac address of the mini and make a skill for the mini.  I would suggest using the invocation name as a zone name.  example "the tv" for the Genie, and "the bedroom tv" for the mini.  Pretty much making zones.

the versions that would be easiest for the mini would be 
the voice guide and the mini genie.

**Comment by reedh11** [comment]
Ok that makes sense.  Thanks.

**Comment by reedh11** [comment]
got it working, such a silly mistake, it's kind of embarrassing.  On the genie index I had deleted &clientAddr and only had the Mac # in there.  

Thanks again for all the help.

**Comment by bklavet** [comment]
Awesome!!! have fun! Happy new year!

**Comment by reedh11** [comment]
Happy New Year.
