### ISSUE TITLE
TBS not working

### ISSUE THREAD

**Issue by StarfighterJ** [bklavet/Echo-skill-to-control-Directv#68]
I ran a test on all the Custom Slot Values all seem to work, but TBS. I am getting I don't Understand.

**Comment by bklavet** [comment]
when I typed tbs in the simulator it is going to lambda as "tbs"  another way alexa could interpret it is "t.b.s."
i will update the index on that, but for yours to work, go to the index and find this
case "TBS":
path = '/tv/tune?major=247';
                
break;

to this:
case "TBS":
case "t.b.s.":
case "tbs":
path = '/tv/tune?major=247';
                
break;
then if you want, edit the Custom Slot Types (Control_List) and add t.b.s. and tbs.  Then save

That should work

**Comment by StarfighterJ** [comment]
That worked . Also Custom Slot types DID not like both TBS and tbs in there. and FYI tbs in lower case will work in Simulator but ALexa ask TV it will not
So now the Custome Slots types is:
TBS
t.b.s.

**Comment by bklavet** [comment]
i just used the mic option on the test simulator beta and it picked up tbs as t.b.s.
TBS is the same as tbs.... I wouldn't have thought that but you are correct, thanks!
