### ISSUE TITLE
Having trouble opening port 8080

### ISSUE THREAD

**Issue by jasands** [bklavet/Echo-skill-to-control-Directv#71]
Will someone that has successfully opened port 8080 on a Uverse router please tell me what you did or better still send me a screen shot of how you did it. I am very dumb when it comes to this sort of thing.

**Comment by bklavet** [comment]
https://www.att.com/esupport/article.html#!/u-verse-high-speed-internet/KM1010280

select your modem and follow the directions. I think this looks like a good place to find out.

B

**Comment by jasands** [comment]
Yea....I've been there and tried it and it didn't work. That was before I
could see my GENIE as active on my router. I will try it again tonight when
I get home.

**Comment by jasands** [comment]
My problem is when I get to #10 I don't know what to put in those fields to
open port 8080 to control my GENIE with Alexa.

**Comment by jasands** [comment]
Would you look at this video and tell me if I put 8080 where he puts his
port # and if there is something else I need to do?

**Comment by vmweaver** [comment]
@jasands  I don't see a video linked?

**Comment by bklavet** [comment]
jasands is up and running, closing issue.
