### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by sakau2007** [bklavet/Echo-skill-to-control-Directv#9]
I am stuck at the last step. Everything seems to be successful but when I get to the service simulator and type in go to cnn for the utterance, I get the error "remote endpoint could not be called, or the response it returned was invalid."

I've placed the DirecTV receiver in the DMZ. From a broswer, when I go to http://192.168.x.x:8080/remote/processKey?key=pause&hold=keyPress I get the following text to display:

{
  "hold": "keyPress",
  "key": "pause",
  "status": {
    "code": 200,
    "commandResult": 0,
    "msg": "OK.",
    "query": "/remote/processKey?key=pause&hold=keyPress"
  }
}

However, DirecTV is not actually pausing.

Any ideas what the issue could be?

**Comment by bklavet** [comment]
Is this a genie mini receiver?

**Comment by sakau2007** [comment]
EDIT: No it is not. It is an HR-22

**Comment by bklavet** [comment]
The response you are getting in the browser looks like it should be working.  If the receiver can't be controlled by this method, the skill won't do any better, but what's confusing is with that response coming from the receiver, I would think the skill would send a confirmation and see the remote endpoint.

One thing that you might try from your browser is to edit the command and add the mac address like the mini genie's and see if that controls the receiver locally (check the other issues for mini genie for details)

You sure you have your wan IP in the index file?

**Comment by sakau2007** [comment]
The IP was definitely correct but now that I think about it, I did turn the modem off and back on in an attempt to get things working and it is possible I was assigned a new WAN IP. I'm not sure if I am static or dynamic. I will double check that when I get back home. If that isn't the issue, I will give the MAC Address a try and report back. Thanks for your support.

**Comment by sakau2007** [comment]
So when I put the MAC address in, it works, sort of. It works in the testing "go to cnn". And when I tell the Echo "Alexa, tell DirecTV to go to CNN" Alexa responds with "OK" as if the command is recognized and accepted but the channel isn't changed.

**Comment by ChipHappens** [comment]
Try putting MAC address in all caps with no colons...i think that is how i got it to work.

**Comment by sakau2007** [comment]
Yeah I am using all caps and no colons for the mac address.

**Comment by ChipHappens** [comment]
http://108.X.X.X:8080/remote/processKey?key=chanup&hold=keyPress&clientAddr=2994X5X4X3XX;

**Comment by bklavet** [comment]
Something to try for the channel like CNN would be to change the Index file path to something like this
 /tv/tune?major=202&clientAddr=xxxxxxxxxxxx  
this worked for a mini genie and should work with any receiver.  This could be tested from a browser on the lan too.  
If this works for you, you would want to alter the path for all the channel presets to this style.
 ChipHappens showed how the path should look for remote buttons like pause,play, etc.  That style could also be tested from a browser session on the local lan. Having Alexa respond with OK is bitter sweet, cause it means the skill is talking to aws lambda and everything is getting to your endpoint, just need to figure out how to tweak the index file to play with your receiver.  If you can get it to do some of this from a browser, then you know the directv receiver is working.
